export type AnswerType = 'A' | 'B' | 'C' | 'D' | 'E' | 'F';

export const quizQuestions = [
  {
    id: 1,
    question: "陽光穿透城木的窗簾，你第一時間會：",
    answers: [
      { text: "靜靜欣賞光影在木紋地板上的變化", type: "A" },
      { text: "拿起手機，搜尋附近有什麼好吃的早餐", type: "B" },
      { text: "走到窗邊，拍一張俯瞰紅磡街景的照片", type: "C" },
      { text: "直接換好衣服，出門隨便走一圈", type: "D" },
      { text: "腦海閃過：夜晚這裡應該會更有感覺", type: "E" },
      { text: "同身邊的人聊兩句，問下附近有咩好去處", type: "F" },
    ],
  },
  {
    id: 2,
    question: "在城木的大堂準備出發，吸引你目光的是：",
    answers: [
      { text: "簡約木系設計帶來的寧靜氛圍", type: "A" },
      { text: "大堂空氣中隱約傳來的早餐香氣", type: "B" },
      { text: "牆上充滿設計感的藝術裝飾", type: "C" },
      { text: "門外街道的流動感，讓人想立刻走出去", type: "D" },
      { text: "光線打在牆面上的陰影變化", type: "E" },
      { text: "大堂裡人與人之間的互動", type: "F" },
    ],
  },
  {
    id: 3,
    question: "踏出酒店大門那一刻，撲面而來的空氣讓你覺得：",
    answers: [
      { text: "帶點清晨的微涼與清新", type: "A" },
      { text: "混雜著遠處茶餐廳飄來的麵包香", type: "B" },
      { text: "有種畫面感，很想記錄下來", type: "C" },
      { text: "讓人想順著這股氣味走進街區", type: "D" },
      { text: "帶著城市剛甦醒的氣氛", type: "E" },
      { text: "夾雜著人來人往的生活氣息", type: "F" },
    ],
  },
  {
    id: 4,
    question: "經過一間老字號冰室，最吸引你的氣味是：",
    answers: [
      { text: "濃郁微澀的港式奶茶香", type: "A" },
      { text: "剛出爐、熱騰騰的蛋撻牛油香", type: "B" },
      { text: "鐵板上滋滋作響的黑椒汁香味", type: "C" },
      { text: "整條街混在一起的生活氣味", type: "D" },
      { text: "空氣中那種舊區特有的味道", type: "E" },
      { text: "店內熱鬧人聲混著食物香氣", type: "F" },
    ],
  },
  {
    id: 5,
    question: "抬頭看到一棟唐樓的外牆，你最留意的是：",
    answers: [
      { text: "斑駁油漆留下的歲月痕跡", type: "A" },
      { text: "窗邊晾曬著的色彩繽紛的衣服", type: "B" },
      { text: "充滿幾何美感的復古花窗玻璃", type: "C" },
      { text: "想走進這棟樓看看裡面", type: "D" },
      { text: "光影在牆面形成的層次", type: "E" },
      { text: "陽台上人與人之間的互動", type: "F" },
    ],
  },
  {
    id: 6,
    question: "觀音廟飄出的檀香味，給你的感覺是：",
    answers: [
      { text: "沉澱心靈，讓思緒平靜下來", type: "A" },
      { text: "帶點神秘，充滿傳統文化的味道", type: "B" },
      { text: "適合配上一段慢動作的 Reels 畫面", type: "C" },
      { text: "讓人想了解這個地方背後的故事", type: "D" },
      { text: "有一種時間停住的感覺", type: "E" },
      { text: "讓人聯想到人群與信仰的連結", type: "F" },
    ],
  },
  {
    id: 7,
    question: "在小巷中發現一間沒有招牌的隱世小店，你會：",
    answers: [
      { text: "站在門外觀察一下它的裝潢風格", type: "A" },
      { text: "毫不猶豫地推門進去看看有什麼好吃的", type: "B" },
      { text: "先在 IG 搜尋一下這間店有沒有人打卡", type: "C" },
      { text: "直接走進去，看看會遇到什麼", type: "D" },
      { text: "心想：夜晚再來應該會更有感覺", type: "E" },
      { text: "同店主聊兩句，看看有什麼推薦", type: "F" },
    ],
  },
  {
    id: 8,
    question: "來到紅磡海濱，迎面吹來的海風讓你覺得：",
    answers: [
      { text: "吹散了一天的疲憊，無比舒暢", type: "A" },
      { text: "帶點海水的鹹味，是屬於城市的氣息", type: "B" },
      { text: "剛好把頭髮吹起，很適合拍一段 Vlog", type: "C" },
      { text: "想沿著海邊一路走下去", type: "D" },
      { text: "讓人想留到夜晚再感受這片海風", type: "E" },
      { text: "想同身邊的人分享這一刻", type: "F" },
    ],
  },
  {
    id: 9,
    question: "聽著海浪拍打岸邊的聲音，你會聯想到：",
    answers: [
      { text: "一首節奏緩慢的輕音樂", type: "A" },
      { text: "晚上去吃一頓豐盛海鮮大餐的衝動", type: "B" },
      { text: "電影裡主角在海邊散步的畫面", type: "C" },
      { text: "像在引導你走向下一個地方", type: "D" },
      { text: "夜晚海邊的靜與遠方城市聲音", type: "E" },
      { text: "想同人坐低慢慢傾偈", type: "F" },
    ],
  },
  {
    id: 10,
    question: "夕陽把海面染成金黃色，這時你最想：",
    answers: [
      { text: "找張長椅坐下，什麼都不做，只看日落", type: "A" },
      { text: "買一罐冰凍的啤酒或汽水，邊喝邊看", type: "B" },
      { text: "瘋狂連拍，捕捉光線最完美的一刻", type: "C" },
      { text: "看完日落繼續走，探索其他地方", type: "D" },
      { text: "等天完全黑下來，看城市燈光亮起", type: "E" },
      { text: "同身邊的人一起看，順便聊聊天", type: "F" },
    ],
  },
  {
    id: 11,
    question: "結束一天的紅磡探索，晚上回到酒店房內，你最想做什麼？",
    answers: [
      { text: "泡一個熱水浴，然後靜靜放空", type: "A" },
      { text: "打開外賣 App，點一份宵夜", type: "B" },
      { text: "整理今天拍的照片和影片，上傳 IG", type: "C" },
      { text: "回想今天走過的地方", type: "D" },
      { text: "站在窗邊，看夜晚城市的燈光", type: "E" },
      { text: "和朋友聊今天的經歷", type: "F" },
    ],
  },
  {
    id: 12,
    question: "睡前閉上眼睛，今天最讓你難忘的「紅磡氣味」是：",
    answers: [
      { text: "觀音廟的檀香與海濱的微風", type: "A" },
      { text: "冰室的奶茶香與街邊的雞蛋仔", type: "B" },
      { text: "充滿新鮮感與未知的城市氣息", type: "C" },
      { text: "街區與空間交織的氣味", type: "D" },
      { text: "夜晚空氣中特有的靜謐氣息", type: "E" },
      { text: "人群與生活流動的氣息", type: "F" },
    ],
  },
  {
    id: 13,
    question: "如果要為今天的紅磡之旅選一首背景音樂，你會選：",
    answers: [
      { text: "一首沒有歌詞的治癒系純音樂", type: "A" },
      { text: "一首節奏輕快、充滿活力的流行曲", type: "B" },
      { text: "一首帶點復古感、適合做 Reels BGM 的歌", type: "C" },
      { text: "一段帶有城市節奏感的聲音", type: "D" },
      { text: "一首氛圍感強的電子 / ambient 音樂", type: "E" },
      { text: "一首適合與人分享、輕鬆聊天的音樂", type: "F" },
    ],
  },
];
